import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useState } from "react";

import { CreateGame } from "@/components/CreateGame/CreateGame";
import { Game } from "@/components/Game/Game";

import { useFetchQuestionsQuery } from "@/features/questions/questions.slice";
import { Backdrop } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const [amount, setAmount] = useState(0);

    const handleSubmit = (amount: number) => {
        setAmount(amount);
    };

    const handleClear = () => setAmount(0);

    const { data, isFetching } = useFetchQuestionsQuery(amount);

    const questions = data?.results;

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
            </Head>
            <main className={styles.main}>
                <CreateGame open={!amount} setQuestionsAmount={handleSubmit} />

                {amount && isFetching && (
                    <Backdrop
                        open={true}
                        sx={{
                            color: "#fff",
                            zIndex: (theme) => theme.zIndex.drawer + 1,
                        }}
                    />
                )}

                {amount && questions?.length && (
                    <Game questions={questions} clearQuestions={handleClear} />
                )}
            </main>
        </>
    );
}
